// ===== DADOS MOCK - AnimalListen Pro =====
// Estes dados simulam o banco de dados. No futuro, serão substituídos pela API real.

// Gera número de prontuário único (6 dígitos aleatórios)
export function generateProntuarioNumber() {
  return String(Math.floor(100000 + Math.random() * 900000));
}

export const mockProntuarios = [
  {
    id: 1,
    numero_prontuario: '384720',
    tutor_nome: 'João Silva',
    tutor_cpf: '123.456.789-00',
    tutor_telefone: '(11) 99999-1234',
    tutor_email: 'joao@email.com',
    tutor_endereco: 'Rua das Flores, 123 - São Paulo/SP',
    animal_nome: 'Rex',
    animal_especie: 'Cão',
    animal_raca: 'Golden Retriever',
    animal_idade: '5 anos',
    animal_sexo: 'Macho',
    animal_peso: 32.5,
    animal_microchip: '981000000012345',
    queixa_principal: 'Vômito e diarreia há 2 dias',
    historico_doenca: 'Animal começou a apresentar vômito após ingestão de alimento estragado. Diarreia aquosa sem sangue.',
    sintomas: ['Vômito', 'Diarreia', 'Apatia', 'Inapetência'],
    comportamento: ['Apático', 'Sem apetite'],
    temperatura: 39.2,
    frequencia_cardiaca: 120,
    frequencia_respiratoria: 28,
    mucosas: 'Rosadas',
    palpacao_abdominal: 'Sensibilidade à palpação em região epigástrica',
    suspeita_diagnostica: 'Gastroenterite aguda',
    exames_solicitados: ['Hemograma', 'Bioquímico'],
    tratamento_prescrito: 'Metoclopramida 1ml a cada 8h, Dipirona 1ml SOS',
    medicamentos: ['Metoclopramida 1ml 8/8h', 'Dipirona 1ml SOS'],
    observacoes_gerais: 'Animal hidratado, mucosas rosadas. Sem sinais de dor intensa.',
    recomendacoes: 'Jejum de 12h, oferecer água aos poucos. Retorno em 3 dias.',
    data_atendimento: '2026-03-17T10:00:00',
  },
  {
    id: 2,
    numero_prontuario: '519836',
    tutor_nome: 'Maria Santos',
    tutor_cpf: '987.654.321-00',
    tutor_telefone: '(11) 98888-5678',
    tutor_email: 'maria@email.com',
    tutor_endereco: 'Av. Paulista, 456 - São Paulo/SP',
    animal_nome: 'Mimi',
    animal_especie: 'Gato',
    animal_raca: 'Siamês',
    animal_idade: '3 anos',
    animal_sexo: 'Fêmea Castrada',
    animal_peso: 4.2,
    animal_microchip: '',
    queixa_principal: 'Espirros frequentes e secreção nasal',
    historico_doenca: 'Quadro de espirros há 5 dias. Secreção nasal serosa.',
    sintomas: ['Espirros', 'Secreção nasal', 'Lacrimejamento'],
    comportamento: ['Ativo', 'Comendo normalmente'],
    temperatura: 38.8,
    frequencia_cardiaca: 180,
    frequencia_respiratoria: 30,
    mucosas: 'Rosadas',
    palpacao_abdominal: 'Sem alterações',
    suspeita_diagnostica: 'Rinotraqueíte viral felina',
    exames_solicitados: ['PCR para herpesvírus'],
    tratamento_prescrito: 'L-lisina 500mg/dia, limpeza nasal com soro fisiológico',
    medicamentos: ['L-lisina 500mg/dia', 'Soro fisiológico nasal 3x/dia'],
    observacoes_gerais: 'Animal em bom estado geral. Alimentação normal.',
    recomendacoes: 'Isolar de outros gatos. Retorno em 7 dias.',
    data_atendimento: '2026-03-16T14:30:00',
  },
  {
    id: 3,
    numero_prontuario: '672914',
    tutor_nome: 'Carlos Oliveira',
    tutor_cpf: '456.789.123-00',
    tutor_telefone: '(11) 97777-9012',
    tutor_email: 'carlos@email.com',
    tutor_endereco: 'Rua Augusta, 789 - São Paulo/SP',
    animal_nome: 'Thor',
    animal_especie: 'Cão',
    animal_raca: 'Bulldog Francês',
    animal_idade: '2 anos',
    animal_sexo: 'Macho Castrado',
    animal_peso: 12.8,
    animal_microchip: '981000000067890',
    queixa_principal: 'Coceira intensa e vermelhidão na pele',
    historico_doenca: 'Prurido generalizado há 10 dias. Piora progressiva.',
    sintomas: ['Prurido', 'Eritema', 'Alopecia focal'],
    comportamento: ['Inquieto', 'Se coçando frequentemente'],
    temperatura: 38.5,
    frequencia_cardiaca: 110,
    frequencia_respiratoria: 24,
    mucosas: 'Rosadas',
    palpacao_abdominal: 'Sem alterações',
    suspeita_diagnostica: 'Dermatite atópica',
    exames_solicitados: ['Raspado cutâneo', 'Citologia de pele'],
    tratamento_prescrito: 'Apoquel 5.4mg 1x/dia, banho com shampoo antisséptico 2x/semana',
    medicamentos: ['Apoquel 5.4mg 1x/dia', 'Shampoo Clorexidina 2x/semana'],
    observacoes_gerais: 'Lesões predominantes em região axilar e interdigital.',
    recomendacoes: 'Evitar gramado. Usar roupa hipoalergênica. Retorno em 15 dias.',
    data_atendimento: '2026-03-15T09:00:00',
  },
  {
    id: 4,
    numero_prontuario: '201458',
    tutor_nome: 'João Silva',
    tutor_cpf: '123.456.789-00',
    tutor_telefone: '(11) 99999-1234',
    tutor_email: 'joao@email.com',
    tutor_endereco: 'Rua das Flores, 123 - São Paulo/SP',
    animal_nome: 'Rex',
    animal_especie: 'Cão',
    animal_raca: 'Golden Retriever',
    animal_idade: '5 anos',
    animal_sexo: 'Macho',
    animal_peso: 32.5,
    animal_microchip: '981000000012345',
    queixa_principal: 'Vacinação anual de rotina',
    historico_doenca: 'Sem queixas. Animal saudável para vacinação.',
    sintomas: [],
    comportamento: ['Ativo', 'Normal'],
    temperatura: 38.5,
    frequencia_cardiaca: 100,
    frequencia_respiratoria: 22,
    mucosas: 'Rosadas',
    palpacao_abdominal: 'Sem alterações',
    suspeita_diagnostica: 'Animal saudável — vacinação preventiva',
    exames_solicitados: [],
    tratamento_prescrito: 'V10 aplicada. Próxima dose em 1 ano.',
    medicamentos: ['V10 (Vacina polivalente)'],
    observacoes_gerais: 'Animal em excelente estado geral.',
    recomendacoes: 'Retorno anual para reforço vacinal.',
    data_atendimento: '2026-02-10T09:00:00',
  },
];

export const mockInternacoes = [
  {
    id: 1,
    animal_nome: 'Buddy',
    animal_especie: 'Cão',
    animal_raca: 'Labrador',
    animal_idade: '7 anos',
    animal_peso: 30,
    animal_microchip: '981000000099999',
    tutor_nome: 'Ana Paula Costa',
    tutor_cpf: '111.222.333-44',
    tutor_telefone: '(11) 96666-1234',
    foto: null,
    motivo: 'Cirurgia ortopédica - fratura de fêmur',
    data_internacao: '2026-03-15T08:00:00',
    status: 'estavel',
    registros: [
      { id: 1, tipo: 'bpm', valor: '90', hora: '2026-03-17T08:00:00', notas: 'FC estável' },
      { id: 2, tipo: 'temperatura', valor: '38.5', hora: '2026-03-17T08:00:00', notas: 'Temperatura normal' },
      { id: 3, tipo: 'alimentacao', valor: 'Sim', hora: '2026-03-17T07:30:00', notas: 'Ração pastosa 200g - comeu tudo' },
      { id: 4, tipo: 'medicacao', valor: 'Meloxicam 0.5mg', hora: '2026-03-17T08:00:00', notas: 'Analgésico administrado' },
      { id: 5, tipo: 'hidratacao', valor: 'Ringer Lactato 500ml', hora: '2026-03-17T06:00:00', notas: 'Fluidoterapia IV' },
      { id: 6, tipo: 'evolucao', valor: 'Estável', hora: '2026-03-17T09:00:00', notas: 'Animal alerta, sem dor aparente. Curativo limpo.' },
      { id: 7, tipo: 'bpm', valor: '88', hora: '2026-03-17T12:00:00', notas: 'FC estável pós-almoço' },
      { id: 8, tipo: 'alimentacao', valor: 'Sim', hora: '2026-03-17T12:00:00', notas: 'Ração pastosa 200g - comeu 80%' },
      { id: 9, tipo: 'temperatura', valor: '38.6', hora: '2026-03-17T12:00:00', notas: '' },
    ],
  },
  {
    id: 2,
    animal_nome: 'Luna',
    animal_especie: 'Gato',
    animal_raca: 'Persa',
    animal_idade: '4 anos',
    animal_peso: 3.8,
    animal_microchip: '',
    tutor_nome: 'Roberto Mendes',
    tutor_cpf: '555.666.777-88',
    tutor_telefone: '(11) 95555-6789',
    foto: null,
    motivo: 'Insuficiência renal aguda',
    data_internacao: '2026-03-16T14:00:00',
    status: 'critico',
    registros: [
      { id: 1, tipo: 'bpm', valor: '200', hora: '2026-03-17T06:00:00', notas: 'Taquicardia' },
      { id: 2, tipo: 'temperatura', valor: '37.2', hora: '2026-03-17T06:00:00', notas: 'Hipotermia leve' },
      { id: 3, tipo: 'alimentacao', valor: 'Não', hora: '2026-03-17T07:00:00', notas: 'Recusou alimentação' },
      { id: 4, tipo: 'medicacao', valor: 'Ondansetrona 0.5mg', hora: '2026-03-17T06:30:00', notas: 'Anti-emético IV' },
      { id: 5, tipo: 'hidratacao', valor: 'NaCl 0.9% 200ml', hora: '2026-03-17T06:00:00', notas: 'Fluidoterapia IV contínua' },
      { id: 6, tipo: 'evolucao', valor: 'Crítico', hora: '2026-03-17T08:00:00', notas: 'Animal prostrado, desidratação moderada. Ureia e creatinina elevadas.' },
      { id: 7, tipo: 'bpm', valor: '190', hora: '2026-03-17T12:00:00', notas: 'Leve melhora' },
      { id: 8, tipo: 'temperatura', valor: '37.8', hora: '2026-03-17T12:00:00', notas: 'Temperatura subindo' },
    ],
  },
  {
    id: 3,
    animal_nome: 'Pipoca',
    animal_especie: 'Cão',
    animal_raca: 'SRD',
    animal_idade: '10 anos',
    animal_peso: 8.5,
    animal_microchip: '981000000054321',
    tutor_nome: 'Fernanda Lima',
    tutor_cpf: '999.888.777-66',
    tutor_telefone: '(11) 94444-3456',
    foto: null,
    motivo: 'Pós-operatório - retirada de tumor mamário',
    data_internacao: '2026-03-17T07:00:00',
    status: 'observacao',
    registros: [
      { id: 1, tipo: 'bpm', valor: '100', hora: '2026-03-17T10:00:00', notas: 'Acordando da anestesia' },
      { id: 2, tipo: 'temperatura', valor: '37.8', hora: '2026-03-17T10:00:00', notas: 'Hipotermia pós-anestésica leve' },
      { id: 3, tipo: 'alimentacao', valor: 'Não', hora: '2026-03-17T12:00:00', notas: 'Jejum pós-cirúrgico' },
      { id: 4, tipo: 'medicacao', valor: 'Tramadol 2mg/kg', hora: '2026-03-17T10:30:00', notas: 'Analgesia pós-operatória' },
      { id: 5, tipo: 'evolucao', valor: 'Em observação', hora: '2026-03-17T11:00:00', notas: 'Recuperando anestesia. Reflexos presentes. Curativo seco e limpo.' },
    ],
  },
];

export const statusLabels = {
  estavel: 'Estável',
  critico: 'Crítico',
  observacao: 'Em Observação',
  alta: 'Alta',
};

export const statusClasses = {
  estavel: 'badge-stable',
  critico: 'badge-critical',
  observacao: 'badge-observation',
  alta: 'badge-discharged',
};

export const tipoRegistroLabels = {
  bpm: 'Frequência Cardíaca',
  temperatura: 'Temperatura',
  alimentacao: 'Alimentação',
  medicacao: 'Medicação',
  hidratacao: 'Hidratação',
  evolucao: 'Evolução',
};

export const tipoRegistroIcons = {
  bpm: 'Heart',
  temperatura: 'Thermometer',
  alimentacao: 'UtensilsCrossed',
  medicacao: 'Pill',
  hidratacao: 'Droplets',
  evolucao: 'FileText',
};
